# Build a hugo website
trigger: none

pr:
  - master

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Hugo_Build
        displayName: Hugo_Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: CmdLine@2
            displayName: Install Hugo
            inputs:
              script: |
                sudo apt update && sudo apt install hugo
          - task: CmdLine@2
            displayName: Hugo_Build
            inputs:
              script: |
                hugo
              workingDirectory: "$(Build.SourcesDirectory)"