baseURL: https://gabrieljean.com

languageCode: en-us
title: "Gabriel Jean"
theme: "toha"

# defaultContentLanguage: us
# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

  fr:
    languageName: Français
    weight: 2

# Enable Google Analytics
googleAnalytics: UA-203769780-1
# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/GabrielJean/Portfolio

  # specify whether you want to write some blog posts or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: false

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  background: "images/site/background.jpg"

  logo:
    main: images/author/avatar.jpg
    inverted: images/author/avatar.jpg
    favicon: images/author/avatar.jpg
